server:
  port: 8080
spring:
  application:
    name: fraud
  datasource:
    username: rjecbgkiqatnpq
    password: fa61073afbd0d204791d1b8cb0cb199dc5fba986587afb84209f90a06bf14bbf
    url: jdbc:postgresql://ec2-18-235-114-62.compute-1.amazonaws.com:5432/d75oh60khp86ie
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect